### ISSUE TITLE
Nintendo switch port is great!

### ISSUE THREAD

**Issue by fennectech** [fgsfdsfgs/openmw#8]
So far ive been using openmw to do my first (modded) playthrough of morrowind.  Thank you for this verry awesome project and I hope to be helpful to you. I would be very willing to test things for you.   Thank you :)

**Comment by fgsfdsfgs** [comment]
Thank you, I'm glad you like it. However this is not really an issue. If you have any comments or questions, better use the [GBATemp](https://gbatemp.net/threads/openmw-for-switch.540250/) release thread or contact me on IRC (fgsfds on EFNet or freenode) or Discord (fgsfds#6988).

If you want to contribute code or report bugs, create issues or PRs on this repository.
